/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eventkampus;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Try WIguna
 */
public final class manageEvent extends javax.swing.JFrame {
    private String idevent ="";
    private String Sk = "";
    private String NamaEvent= "";
    private String instansi="";
    private String Tanggal="";
    private String Tempat="";
    private String Kategori="";
    private String Harga="";
    private Blob Foto;
    private String Deskripsi="";
     private String CurrentDate="";
     private String id_admin;
    
    
    
    

    /**
     * Creates new form manageEvent
     */
    public manageEvent() {
        initComponents();
        this.setTabel1();
        this.tglSkg();
        this.setTabel2();
    }
    
    public void tglSkg(){
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        CurrentDate=(dateFormat.format(cal.getTime()));
        txtTglSkr.setText(CurrentDate);
    }
    
    public void Updatetbl1(){
            String sql = "select * from tb_event_belumvalid ;";
        try{
            DBConnection buka = new DBConnection();
          Connection con =(Connection) buka.connect();
           PreparedStatement ps = con.prepareStatement(sql);
          Statement st =(Statement) con.createStatement();
          ResultSet rs;
                rs = st.executeQuery(sql);
          rs=ps.executeQuery(sql);
          setTabel1();          
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
}
  public void Updatetbl2(){
            String sql = "select * from tb_event ;";
        try{
            DBConnection buka = new DBConnection();
          Connection con =(Connection) buka.connect();
           PreparedStatement ps = con.prepareStatement(sql);
          Statement st =(Statement) con.createStatement();
          ResultSet rs;
                rs = st.executeQuery(sql);
          rs=ps.executeQuery(sql);
          setTabel2();          
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblevent_belumvalid = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSk = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtInstansi = new javax.swing.JTextField();
        txtIDevent = new javax.swing.JTextField();
        btnvalid = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTglSkr = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblevent_belumvalid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblevent_belumvalid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblevent_belumvalidMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblevent_belumvalid);

        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEvent);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VALIDASI EVENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SK");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Event");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Instansi");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EventID");

        btnvalid.setText("Valid");
        btnvalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSk, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(txtInstansi, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtIDevent))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIDevent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnvalid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HISTORY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Tanggal Sekarang");

        jLabel7.setText("Tanggal Event");

        jLabel8.setText("Nama Event");

        txtTglSkr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglSkrActionPerformed(evt);
            }
        });

        jButton1.setText("Kembali");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTglSkr, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txtTgl, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTglSkr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled-5.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(231, 231, 231))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblevent_belumvalidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblevent_belumvalidMouseClicked
        // TODO add your handling code here:
      try{
            int row = tblevent_belumvalid.getSelectedRow();
            String id_event  = (String) tblevent_belumvalid.getValueAt(row, 0);
            DBConnection buka = new DBConnection();
            Connection con = (Connection) buka.connect();
            Statement st = (Statement) con.createStatement();
            String tampil = "select * from tb_event_belumvalid where id_event_belumvalid='"+id_event+"';";
            ResultSet rs = st.executeQuery(tampil);
            txtIDevent.setText(tblevent_belumvalid.getModel().getValueAt(row, 0).toString());
            txtSk.setText(tblevent_belumvalid.getModel().getValueAt(row, 1).toString());
            txtNama.setText(tblevent_belumvalid.getModel().getValueAt(row, 2).toString());
            txtInstansi.setText(tblevent_belumvalid.getModel().getValueAt(row, 3).toString());
        }
        catch (SQLException ex){
            Logger.getLogger(manageEvent.class.getName()).log(Level.SEVERE,null,ex);
        }    
           
    }//GEN-LAST:event_tblevent_belumvalidMouseClicked

    private void btnvalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidActionPerformed
            try {                                         
                // TODO add your handling code here:
                int row = tblevent_belumvalid.getSelectedRow();
                String id_event  = (String) tblevent_belumvalid.getValueAt(row, 0);
                DBConnection buka = new DBConnection();
                Connection con = (Connection) buka.connect();
                Statement st = (Statement) con.createStatement();
                String sql = "select * from tb_event_belumvalid where id_event_belumvalid='"+id_event+"';";
                ResultSet rs = st.executeQuery(sql);
                
                try {
                    while(rs.next()){
                        Sk = rs.getString("sk");
                        NamaEvent = rs.getString("nama_event");
                        instansi = rs.getString("instansi");
                        Tanggal = rs.getString("tanggal_acara");
                        Tempat = rs.getString("tempat_acara");
                        Kategori = rs.getString("kategori");
                        Harga = rs.getString("harga");
                        Deskripsi= rs.getString("deskripsi");
                        idevent =rs.getString("id_event_belumvalid");
                        id_admin=rs.getString("id_admin");
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(manageEvent.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                String query = "INSERT INTO tb_event(id_event,sk,nama_event, instansi,tanggal_acara,tempat_acara,kategori,harga,deskripsi,id_admin)"
                        + " VALUES('"+idevent+"','" + Sk + "', '" + NamaEvent + "', '" + instansi + "', '" + Tanggal + "', '" + Tempat + "', '" + Kategori + "','" + Harga + "', '" + Deskripsi + "','"+id_admin+"');";
                int res = st.executeUpdate(query);
                String query1 = "DELETE FROM tb_event_belumvalid WHERE sk='"+Sk+"';";
                int res1 = st.executeUpdate(query1);
            } catch (SQLException ex) {
            Logger.getLogger(manageEvent.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(this, "Validasi Event berhasil dilakukan");
            Updatetbl1();
            
            
    }//GEN-LAST:event_btnvalidActionPerformed

    private void txtTglSkrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglSkrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglSkrActionPerformed

    private void tblEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventMouseClicked
        // TODO add your handling code here:
         try{
            int row = tblEvent.getSelectedRow();
            String id_event  = (String) tblEvent.getValueAt(row, 0);
            DBConnection buka = new DBConnection();
            Connection con = (Connection) buka.connect();
            Statement st = (Statement) con.createStatement();
            String tampil = "select * from tb_event where id_event='"+id_event+"';";
            ResultSet rs = st.executeQuery(tampil);
            txtname.setText(tblEvent.getModel().getValueAt(row, 2).toString());
            txtTgl.setText(tblEvent.getModel().getValueAt(row, 4).toString());
        }
        catch (SQLException ex){
            Logger.getLogger(manageEvent.class.getName()).log(Level.SEVERE,null,ex);
        }    
           
    }//GEN-LAST:event_tblEventMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            dashboardsuperadmin dad = null;
            
        try {
            dad = new dashboardsuperadmin ();
        } catch (Exception ex) {
            Logger.getLogger(daftarevent.class.getName()).log(Level.SEVERE, null, ex);
        }
        dad.setVisible(true);
        dad.pack();
        dad.setLocationRelativeTo(null);
        dad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
            manageEvent dad = null;
            
        try {
            dad = new manageEvent ();
        } catch (Exception ex) {
            Logger.getLogger(daftarevent.class.getName()).log(Level.SEVERE, null, ex);
        }
        dad.setVisible(true);
        dad.pack();
        dad.setLocationRelativeTo(null);
        dad.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageEvent().setVisible(true);
            }
        });
    }
       public void setTabel1(){
      int a = 100;
      Object [][] data = new Object[a][10];
      
      try{
          DBConnection buka = new DBConnection();
          Connection con =(Connection) buka.connect();
          Statement st =(Statement) con.createStatement();
          String sql = "select * from tb_event_belumvalid;";
          ResultSet rs = st.executeQuery(sql);
          
          int i=0;
          
          while(rs.next()){
          data[i][0] = rs.getString("id_event_belumvalid");
          data[i][1] = rs.getString("sk");
          data[i][2] = rs.getString("nama_event");
          data[i][3] = rs.getString("instansi");
          data[i][4] = rs.getString("tanggal_acara");
          data[i][5] = rs.getString("tempat_acara");
          data[i][6] = rs.getString("kategori");
          data[i][7] = rs.getString("harga");
          i++;
      }
        String[] setJudul = {"ID Event","No.SK","Nama Event","Instansi","Tgl Acara","Tempat","Kategori","Harga"};
        tblevent_belumvalid.setModel(new DefaultTableModel(data,setJudul));
        data = new Object [i][2];
      }
      catch(Exception sa){
      System.out.println("Gagal Tampil!"+sa.toString());
      
  }
  }
      public void setTabel2(){
      int a = 100;
      Object [][] data = new Object[a][10];
      
      try{
          DBConnection buka = new DBConnection();
          Connection con =(Connection) buka.connect();
          Statement st =(Statement) con.createStatement();
          String sql = "select * from tb_event;";
          ResultSet rs = st.executeQuery(sql);
          
          int i=0;
          
          while(rs.next()){
          data[i][0] = rs.getString("id_event");
          data[i][1] = rs.getString("sk");
          data[i][2] = rs.getString("nama_event");
          data[i][3] = rs.getString("instansi");
          data[i][4] = rs.getString("tanggal_acara");
          data[i][5] = rs.getString("tempat_acara");
          data[i][6] = rs.getString("kategori");
          data[i][7] = rs.getString("harga");
          i++;
      }
        String[] setJudul = {"ID Event","No.SK","Nama Event","Instansi","Tgl Acara","Tempat","Kategori","Harga"};
        tblEvent.setModel(new DefaultTableModel(data,setJudul));
        data = new Object [i][2];
      }
      catch(Exception sa){
      System.out.println("Gagal Tampil!"+sa.toString());
      
  }
  }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvalid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEvent;
    private javax.swing.JTable tblevent_belumvalid;
    private javax.swing.JTextField txtIDevent;
    private javax.swing.JTextField txtInstansi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSk;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtTglSkr;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
