/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Eventkampus;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Try WIguna
 */
public class RegisterEvent extends javax.swing.JFrame {

    /**
     * Creates new form RegisterEvent
     */
    public RegisterEvent() {
        initComponents();
        jLabel13.setText(String.valueOf(adminID.admin_id).toString());
    }
    String ImgPath=null;
    public Connection getConnection () 
    {
        Connection con = null;
         try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_eventkampus?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","");
	    JOptionPane.showMessageDialog(null,"Connected");
	    return con;
        } catch (SQLException ex){
            Logger.getLogger(registerform.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Not Connected");
            return null;
        }
    }
    
     
        public void nama (KeyEvent p){
        if(txtNamaEvent.getText().length()<3  && txtNamaEvent.getText().length()>255){
        p.consume();
        JOptionPane.showMessageDialog(null, "maksimal panjang namaEvent adalah 255 karakter dan minimal 3 karakter", "peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }
         public void instansi (KeyEvent p){
        if(txtInstansi.getText().length()<3  && txtInstansi.getText().length()>100){
        p.consume();
        JOptionPane.showMessageDialog(null, "maksimal panjang Instansi adalah 100 karakter dan minimal 3 karakter", "peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }
        
        public void nosk (KeyEvent p){
        if(txtNoSK.getText().length()>11 || Character.isSpaceChar(p.getKeyChar()) || Character.isAlphabetic(p.getKeyChar())){
        p.consume();
        JOptionPane.showMessageDialog(null, "Maksimal no sk 11 digit tanpa spasi dan hanya angka", "peringatan", JOptionPane.WARNING_MESSAGE);    
        }
        }
         
        public void harga (KeyEvent p){
        if(txtHarga.getText().length()>11 || Character.isSpaceChar(p.getKeyChar()) || Character.isAlphabetic(p.getKeyChar())){
        p.consume();
        JOptionPane.showMessageDialog(null, "Maksimal Harga 11 digit tanpa spasi dan hanya angka", "peringatan", JOptionPane.WARNING_MESSAGE);    
        }
        }
        public void deskripsi (KeyEvent p){
        if(txtDeskripsi.getText().length()<3 && txtDeskripsi.getText().length()>300){
        p.consume();
        JOptionPane.showMessageDialog(null, "maksimal panjang Deskripsi 300 karakter dan minimal 3 karakter", "peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }
         public void tempat (KeyEvent p){
        if(txtTempat.getText().length()>255 ){
        p.consume();
        JOptionPane.showMessageDialog(null, "maksimal panjang  karakter 255", "peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }
    
    //check input file
    
    public boolean checkInputs()
    {
        if(txtNoSK.getText() == null
           ||txtNamaEvent.getText() == null
           || txtInstansi.getText() == null
           || txtDate.getText() == null
           || txtTempat.getText()  == null
           || txtHarga.getText() == null
           || txtInstansi.getText() == null
           || kategori == null
           || txtDeskripsi.getText() == null
            ){
            return false;
            }
        else{
            return true;
           
        }
    
     }
    //resize Image
    public ImageIcon ResizeImage (String imagePath, byte [] pic)
{
	ImageIcon myImage = null;
	if(imagePath !=null)
	{
            myImage=new ImageIcon(imagePath);
	}else{
            myImage = new ImageIcon (pic);
	}
	Image img = myImage.getImage();
	Image img2 = img.getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(),Image.SCALE_SMOOTH);
	ImageIcon image = new ImageIcon(img2);
	return image;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamaEvent = new javax.swing.JTextField();
        txtInstansi = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonPhoto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jButtonUpload = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonSeminar = new javax.swing.JRadioButton();
        jRadioButtonHiburan = new javax.swing.JRadioButton();
        jRadioButtonLomba = new javax.swing.JRadioButton();
        jLabelFoto = new javax.swing.JLabel();
        txtDate = new datechooser.beans.DateChooserCombo();
        jLabel10 = new javax.swing.JLabel();
        txtNoSK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nama Event");

        jLabel3.setText("Instansi");

        jLabel4.setText("Tanggal Acara");

        jLabel5.setText("Tempat Acara");

        jLabel6.setText("Harga");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Deskripsi");

        txtNamaEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaEventActionPerformed(evt);
            }
        });
        txtNamaEvent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaEventKeyTyped(evt);
            }
        });

        txtInstansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstansiActionPerformed(evt);
            }
        });
        txtInstansi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInstansiKeyTyped(evt);
            }
        });

        txtTempat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTempatKeyTyped(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Foto");

        jButtonPhoto.setText("...");
        jButtonPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhotoActionPerformed(evt);
            }
        });

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        txtDeskripsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDeskripsiKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDeskripsi);

        jButtonUpload.setText("Upload");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel9.setText("Kategori");

        buttonGroup1.add(jRadioButtonSeminar);
        jRadioButtonSeminar.setText("Seminar");
        jRadioButtonSeminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSeminarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonHiburan);
        jRadioButtonHiburan.setText("Hiburan");
        jRadioButtonHiburan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHiburanActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonLomba);
        jRadioButtonLomba.setText("Lomba");
        jRadioButtonLomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLombaActionPerformed(evt);
            }
        });

        jLabel10.setText("No.SK");

        txtNoSK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoSKActionPerformed(evt);
            }
        });
        txtNoSK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoSKKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RegisterForm");

        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNamaEvent, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtInstansi, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNoSK)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTempat, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(txtHarga))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jRadioButtonSeminar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButtonHiburan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButtonLomba)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonUpload)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonPhoto)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNoSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButtonPhoto)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jRadioButtonSeminar)
                            .addComponent(jRadioButtonHiburan)
                            .addComponent(jRadioButtonLomba))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonUpload)
                            .addComponent(jButtonCancel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BACK 4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Check_Book_30px.png"))); // NOI18N
        jLabel12.setText("REGISTRASI EVENT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaEventActionPerformed

    private void jButtonPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabelFoto.setIcon(ResizeImage(path, null));
            ImgPath = path;
        }
        else{
            System.out.println("No File Selected");
        }                                                 

    }//GEN-LAST:event_jButtonPhotoActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed
    String kategori;
    private void jRadioButtonSeminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSeminarActionPerformed
        // TODO add your handling code here:
        kategori="Seminar";
    }//GEN-LAST:event_jRadioButtonSeminarActionPerformed

    private void jRadioButtonHiburanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHiburanActionPerformed
        // TODO add your handling code here:
        kategori="Hiburan";
    }//GEN-LAST:event_jRadioButtonHiburanActionPerformed

    private void jRadioButtonLombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLombaActionPerformed
        // TODO add your handling code here:
        kategori="Lomba";
    }//GEN-LAST:event_jRadioButtonLombaActionPerformed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
          if(checkInputs() && ImgPath != null)
       {
           
           try {
               Connection con = getConnection();
               PreparedStatement ps = con.prepareStatement("INSERT INTO tb_event_belumvalid(sk,nama_event, instansi,tanggal_acara,tempat_acara,kategori,harga,deskripsi,id_admin)"
                       + "values(?,?,?,?,?,?,?,?,?)");
               PreparedStatement ps1 = con.prepareStatement("INSERT INTO tb_foto(sk,foto) VALUES(?,?)");
               ps.setString(1, txtNoSK.getText());
               ps.setString(2, txtNamaEvent.getText());
               ps.setString(3, txtInstansi.getText());
               ps.setString(4, txtDate.getText());
               ps.setString(5, txtTempat.getText());
               ps.setString(6, kategori);
               ps.setString(7, txtHarga.getText());
               ps.setString(8, txtDeskripsi.getText());
               ps.setString(9, jLabel13.getText());
               InputStream img = new FileInputStream(new File(ImgPath));
               ps1.setString(1, txtNoSK.getText());
               ps1.setBlob(2, img);
               ps.executeUpdate();
               ps1.executeUpdate();
               
               JOptionPane.showMessageDialog(null, "Data Inserted");
           } 
           catch (FileNotFoundException|SQLException ex) {
               JOptionPane.showMessageDialog(null,ex.getMessage());
           }
       }else{
           JOptionPane.showMessageDialog(null, "One or More Field Are Empty");
       }
       System.out.println("NoSK => "+txtNoSK.getText());   
       System.out.println("NamaEvent => "+txtNamaEvent.getText());
       System.out.println("Instansi => "+txtInstansi.getText());
       System.out.println("Tanggal_acara => "+txtDate.getText());
       System.out.println("Tempat => "+txtTempat.getText());
       System.out.println("Kategori => "+kategori);
       System.out.println("harga => "+txtHarga.getText());
       System.out.println("Deskripsi=> "+txtDeskripsi.getText());
       System.out.println("Foto=> "+ImgPath);
       
    }//GEN-LAST:event_jButtonUploadActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtInstansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstansiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstansiActionPerformed

    private void txtNoSKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoSKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoSKActionPerformed

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
    dashboardadmin dba = new dashboardadmin ();
                dba.setVisible (true);
                setVisible (false);
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void txtNamaEventKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaEventKeyTyped
        nama(evt);
    }//GEN-LAST:event_txtNamaEventKeyTyped

    private void txtInstansiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstansiKeyTyped
        instansi(evt);
    }//GEN-LAST:event_txtInstansiKeyTyped

    private void txtNoSKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoSKKeyTyped
        nosk(evt);
    }//GEN-LAST:event_txtNoSKKeyTyped

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
      harga(evt);
    }//GEN-LAST:event_txtHargaKeyTyped

    private void txtDeskripsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeskripsiKeyTyped
        deskripsi(evt);
    }//GEN-LAST:event_txtDeskripsiKeyTyped

    private void txtTempatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatKeyTyped
       tempat(evt);
    }//GEN-LAST:event_txtTempatKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPhoto;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonHiburan;
    private javax.swing.JRadioButton jRadioButtonLomba;
    private javax.swing.JRadioButton jRadioButtonSeminar;
    private javax.swing.JScrollPane jScrollPane1;
    private datechooser.beans.DateChooserCombo txtDate;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtInstansi;
    private javax.swing.JTextField txtNamaEvent;
    private javax.swing.JTextField txtNoSK;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}
